### PR TITLE
Feature/gradle experimental

### PR DESCRIPTION
**Pull request by clebeaupin**
Also see:
https://github.com/readium/readium-sdk/pull/224

### CODE REVIEW

**Comment by danielweck** [comment]
That's great @clebeaupin ! :)
+ @JCCR 

1) I successfully debugged into hybrid `Java` + `C++` code, directly from Android Studio, on my hardware Android device (Marshmallow 6.0 API 23 - ARMv7). By the way, I haven't tried the Android emulator on my Windows 10 machine, because of `HAXM` / `HyperV` incompatibilities (I don't want to disable the latter for now, and the former is required by Android Studio).

2) I wrote rudimentary (but functioning) cross-platform Gradle tasks to generate the `navigator.epubReadingSystem` Git versioning info, thereby making the Windows-incompatible `epubReadingSystem.sh` shell script unnecessary! :+1: 

3) `MakeHeaders.sh` is also unnecessary (replaced with Gradle copy tasks, if I understand correctly ... Cyrille can you please confirm?), and the Git symbolic links have been replaced with Gradle copy tasks. Therefore, this is now a fully-functioning **cross-platform** Android config!! Good bye Eclipse, welcome Android Studio.

@JCCR could you please test at your end to check everything works as expected. I believe @clebeaupin is on Linux (mainly). I'm on Windows 10 (mainly) and I haven't tested on my secondary dev machine yet (OSX).

**Comment by danielweck** [comment]
By the way, this is the crude (but fully functioning) `navigator.epubReadingSystem` version info Gradle script:
https://github.com/readium/SDKLauncher-Android/blob/feature/gradle-experimental/SDKLauncher-Android/app/build_epubReadingSystem.gradle#L1

It's included from the main app Gradle build config:
https://github.com/readium/SDKLauncher-Android/blob/feature/gradle-experimental/SDKLauncher-Android/app/build.gradle#L97

**Comment by clebeaupin** [comment]
I confirm that MakeHeaders.sh is useless and replaced by standard gradle copy tasks.
On my side, I have tested this gradle project on linux, windows and OS X. I have debug java and C++ code on Android emulator but also on ARM 7.

**Comment by rkwright** [comment]
We need to figure out if we can switch to Android Studio "standard" and use the gradle project without a lot of refactoring since the Standard and Experimental versions of AS using slightly different syntax.

**Comment by danielweck** [comment]
@rkwright LGTM?

**Comment by rkwright** [comment]
I think do, but would like to review it one more time.  Monday, 17 April?

**Comment by danielweck** [comment]
As agreed on the ReadiumSDK concall, LGTM.

**Pull request merged**
