### PR TITLE
Fixes #92

### LINKED ISSUE #92: HTTP cache control headers
See:
https://github.com/readium/readium-sdk/pull/236

### PR DESCRIPTION
**Pull request by olivierkorner**
Adds HTTP caching headers to responses in EpubServer

### CODE REVIEW

**Comment by danielweck** [comment]
Related:
https://github.com/readium/SDKLauncher-OSX/pull/48
https://github.com/readium/readium-sdk/pull/236

**Comment by danielweck** [comment]
Looks Good To Me.
Lets Get This Merged.

PS: I have not tested this PR, just reviewed the code.

Ric?

**Comment by rkwright** [comment]
I agree, merge away

**Comment by msintov** [comment]
@olivierkorner Thank you, Olivier! I have been looking forward to this change.

Did you find that adding these headers improved performance on Android? I am curious which devices/OSes were checked out? Is there an epub you would be able to share with me where the performance improved?

I integrated this change into my local code and did performance testing with an internal epub. I did not see any distinguishable improvement in my case so far. I only tested on a Nexus 7 running KitKat. I was expecting that the page turn time after page 1 would be shortened.

Thank you!

**Comment by danielweck** [comment]
to observe faster web view loads,  there must be repetitive resources amongst HTML documents, if possible large images, fonts, etc.

**Comment by olivierkorner** [comment]
@msintov Yes performance is better on Android as well, but as @danielweck said, the speed gain depends on the EPUB. Here are the gains I measured with two different Fixed Layout EPUBs. I can send them to you by email if you want. The tests were made on an emulated Nexus 5 running Lollipop.
How do you measure performance?

**Ligne aveugle**
	
| no cache | cache | gain |
| --- | --- | --- |
| 412 | 516 | 125% |
| 335 | 299 | 89% |
| 365 | 296 | 81% |
| 353 | 223 | 63% |
| 323 | 295 | 91% |
| 472 | 299 | 63% |
| 463 | 304 | 66% |
| 511 | 342 | 67% |
| 486 | 367 | 75% |
| 460 | 397 | 86% |
| 578 | 350 | 61% |
| 500 | 332 | 66% |
| 443 | 299 | 67% |
| 453 | 395 | 87% |
| 559 | 344 | 62% |
| 465 | 373 | 80% |
| 505 | 321 | 64% |
| 496 | 282 | 57% |
| 334 | 175 | 52% |
| 320 | 204 | 64% |
| --- | --- | --- |
| **8835** | **6411** | **73%** |


**Optical Sound 3**

| no cache | cache | gain |
| --- | --- | --- |
| 283 | 259 | 92% |
| 266 | 224 | 84% |
| 212 | 202 | 96% |
| 240 | 212 | 88% |
| 203 | 172 | 85% |
| 239 | 239 | 100% |
| 277 | 247 | 89% |
| 273 | 232 | 85% |
| 209 | 228 | 109% |
| 336 | 207 | 62% |
| 227 | 243 | 107% |
| 210 | 209 | 100% |
| 297 | 265 | 89% |
| 264 | 225 | 85% |
| 260 | 325 | 125% |
| 340 | 296 | 87% |
| 252 | 229 | 91% |
| 353 | 288 | 82% |
| 242 | 224 | 93% |
| 248 | 228 | 92% |
| --- | --- | --- |
| **5228** | **4754** | **91%** |

**Comment by msintov** [comment]
Hi @olivierkorner ,

I tried with two epubs. I tested on a Nexus 7 2nd gen running KitKat and Samsung Tab 2 running Lollipop, 5.1.1 (not emulated devices). In my testing I don't see a significant difference when caching is used. I am measuring the time between when the page turn is requested and when onPaginationChanged fires.

I hear you that it varies by epub. Perhaps that is the story here.

**Pull request merged**
